### ISSUE TITLE
smelli pins flavio version

### ISSUE THREAD

**Issue by peterstangl** [smelli/smelli#13]
At the moment, smelli pins the flavio version:
https://github.com/smelli/smelli/blob/2235a699d5900cd32e2576e0068f38f4c7b9334b/setup.py#L26
This means that pip will not allow an update of flavio unless smelli is updated first.

I think the reason for pinning is that a new flavio version could introduce updated measurements that include data from older measurement still contained in flavio. Since smelli by default loads all measurements of a given observable, this would lead to some double counting. Such problems are avoided by the pinning.

I see two alternatives:
- instead of including all available measurements in smelli by default and only *explicitly excluding* certain measurements, one could *explicitly include* each single measurement that should be used by smelli.
- one could try to make sure that flavio does not contain measurements that share some data. However, this is not possible if e.g. the combination of Bs->mumu measurements is kept together with the individual measurements.

**Comment by DavidMStraub** [comment]
A third alternative would be to replace the `~=` by `>=`. This would remove the problem with pip (I think). It would still potentially lead to inconsistent results, but we already have the warning for that, so the users should know they have to upgrade. The only problem is that it still forces us to release a new smelli version everytime a new flavio minor version is released, but this shouldn't be a problem; if nothing of relevance changes, we can simply increase the third digit of the smelli release and only change __flavio_version.

**Comment by peterstangl** [comment]
@DavidMStraub, as a temporary fix, I have implemented your suggestion in https://github.com/smelli/smelli/commit/b1725f9b1f3e440fd3b44d0935617478ac6c2667 to be used in smelli 2.0

For a solution of the potential inconsistent results, one might have to address its origin, namely the fact that flavio contains measurements that cannot be combined in a consistent way. Perhaps one could add a new attribute in the `measurements.yml` file in flavio. Something like `exclude: True` to exclude a certain measurement by default without removing it completely from the YAML file.
This would mean that a set of default measurements that can be consistently combined would be defined in flavio and a new flavio version, even with changed default measurements, would not lead to a problem in smelli.
What do you think about such a solution?

**Comment by DavidMStraub** [comment]
Given that smelli is in some sense a curated flavio likelihood, one could even go further and hard-code the `include_measurements` in smelli. This could be simply autogenerated by a script before every
release. This would make adding a new measurement slightly more inconvient for the user, but at the same time prevents them from accidentally adding one without noticing.

The main problem I see is that it will break if a new flavio version *removes* one of the measurements (which did occur regularly in the past), but one could catch that with a meaningful error message (e.g. "measurement XYZ not found. Please check for updated versions of flavio and smelli").
