### ISSUE TITLE
Number of observations

### ISSUE THREAD

**Issue by AlexandreCarvunis** [smelli/smelli#37]
I have been using the ‘number_observation_dict()’ method with the GlobalLikelihood class and something is puzzling me when I try to change the measurements smelli uses. Note that I am using the unreleased v2.2.0.

Here is what I do (after the relevant imports):

gl = GlobalLikelihood(eft="WET", fix_ckm=True, include_likelihoods=['fast_likelihood_quarks_fixckm.yaml’])
gl.number_observations_dict()

Which returns : 

{'fast_likelihood_quarks_fixckm.yaml': 169, 'global': 169}

Then I go in 'smelli/data/yaml/measurements_quarks.yaml’  and replace :

 ‘-ATLAS CMS LHCb combination Bs->mumu 2020 Gaussian’

with eg

'- ATLAS Bs->mumu 2018
- CMS Bs->mumu 2019’

After restarting the kernel, gl.number_observations_dict() gives the same number of observations as before (169) and not 170 as I expected. To sum up : adding more measurements of a given observable in 'measurements_XX.yaml' doesn't increase the number of observations returned by the number_observations_dict() method. I also tried to add 2 multivariate gaussian entries rather than the full likelihood distribution for ATLAS Bs->mumu 2018 and CMS Bs->mumu 2019 and observed the same behavior.

Is this an expected behavior?

Regards, 
Alexandre Carvunis

**Comment by peterstangl** [comment]
Hi Alexandre,

I think the reason for this behavior is that you are using a `FastLikelihood` in which experimental and theoretical uncertainties are approximated as Gaussian and combined in terms of a covariance matrix that is the sum of a experimental and a theoy covariance matrix. These covariance matrices have entries for each *observable*, not for each observation. Therefore, different measurements of the same observable are combined before determining the experimental covariance matrix. And then such a combination is counted as only one d.o.f., which means that for a `FastLikelihood`, the number of observations will always equal the number of observables. @DavidMStraub can you confirm that?

Apart from this, one has to be careful when modifying the list of measurements included in smelli, in particular in the case of a `FastLikelihood`. As mentioned above, a `FastLikelihood` approximates all uncertainties as Gaussian and in the case of non-Gaussian experimental likelihoods, this is done by sampling the full likelihood. Now in the case of B_s,d->mumu, there is the problem that a large part of the region around the central value in the experimental likelihood would extend to negative branching ratios for B_d->mumu, but is cut off at zero. In this case, sampling is also cut off at zero and this leads to an inappropriate Gaussian approximation. This is why the `measurements.yml` in flavio contains an actual Gaussian likelihood for B_s,d->mumu that does not lead to this problem. At the moment, the most recent LHCb measurement is not taken into account, but an updated combination has been determined in [arXiv:2103.13370](https://arxiv.org/abs/2103.13370) and will be added to flavio soon.

**Comment by AlexandreCarvunis** [comment]
Hi Peter,

Thank you for your prompt reply. 

I understand that different measurements of a single observable are combined in `FastLikelihood` and therefore the number of observations will always be equal to the number of observables. I have a follow up question about this. If I call the GlobalLikelihood method with the set of LFU FCNC observables:

`gl = GlobalLikelihood(eft="WET", fix_ckm=True, include_likelihoods=['likelihood_lfu_fcnc.yaml’])`
`gl.number_observations_dict()`

returns `{'likelihood_lfu_fcnc.yaml': 21, 'global': 21}`. Among the observables included, there is `BR(B0->tautau)` which has two measurements : `BaBar Btautau 2005` and `LHCb B->tautau 2017`. If I remove `- BaBar Btautau 2005` from `measurements_lfu_fcnc.yaml`, `gl.number_observations_dict()` returns `{'likelihood_lfu_fcnc.yaml': 20, 'global': 20}`. So this time the number of observations has decreased. Is this because in this case smelli is using `Likelihood` and not `FastLikelihood`?

I am aware of the issue with `FastLikelihood` and the full experimental likelihood of some observables such as BR(B_d->mumu), I only used it because it was the only example I had to ask my question.

**Comment by peterstangl** [comment]
Yes, this is exactly the reason. The 'likelihood_lfu_fcnc.yaml’ is implemented as an instance of `Likelihood` and not of `FastLikelihood`. In this case, different experimental measurements do not have to be combined into a single Gaussian likelihood but can be treated as individual observations. In smelli, there are these two different ways of treating theoretical and experimental uncertainties:
- Theoretical and experimental uncertainties are assumed to be Gaussian and combined in terms of a covariance matrix. This is implemented using `FastLikelihood`.
- Theory uncertainties are neglected and the full (possibly non-Gaussian) experimental likelihood is used. This is implemented using `Likelihood`.

More details can be found in [section 2 of arXiv:1810:07698](https://arxiv.org/pdf/1810.07698.pdf#section.2).

**Comment by AlexandreCarvunis** [comment]
Thank you Peter, this is clear now.
