### ISSUE TITLE
Add mu->e conversion on nuclei to the likelihood

### ISSUE THREAD

**Issue by hoodyn** [smelli/smelli#38]
Hi, I found that mu->e conversion has not been included in smelli (yet). Is there a reason for it? 
I would like to add the observables `CR(mu->e, Ti)` and `CR(mu->e, Au)` and the corresponding measurement that are already in flavio. I'm not sure about your policy - what's the best way to comply with your "standards" so that I can make an acceptable pull request? 
Can I add the corresponding entries `likelihood_lfv.yaml` and `measurements_lfv.yaml` and make a separate file for obseravbles such as 'observables_mue_cr.yaml'?

**Comment by peterstangl** [comment]
Good idea @hoodyn! I think the only reason why mu->e conversion is not included in smelli is that these observables were added to flavio only after the initial release of smelli. I think you could add the observables directly to `observables_lfv.yaml` (if there are no separate files for tau and mu, I don't see why we would have to make one for mu->e conversion) and the measurements to `measurements_lfv.yaml`.
