### ISSUE TITLE
Strange chi^2 results with neutron observables

### ISSUE THREAD

**Issue by MJKirk** [smelli/smelli#40]
I've found a some strange result in smelli that I don't understand.
I'm looking at a certain NP point, as defined by some wilson coefficient, and smelli says there is a reasonable delta chi^2 relative to the SM. But when I look at the observables (in this case the neutron observables in https://github.com/smelli/smelli/blob/master/smelli/data/yaml/observables_n.yaml), the theory predictions are either the same as at the SM point, or they have changed by a tiny amount.
Specifically, I am looking at the pulls using the `obstable` method of `GlobalLikelihoodPoint` - one changes by 0.04, several others by O(10^-15), and the rest by exactly 0, while the chi^2 apparently changes by 4.
I know the pulls as reported by `obstable` can't be exactly summed to get the chi^2 as you have to take into account correlations, but even given that it seems to me hard to explain the result I see.
I am getting the neutron chi^2 values using the custom_likelihood option, maybe there is something I am misusing perhaps?
Below is a (relatively) minimal example that hopefully shows my point:
```python
import numpy as np
import pandas as pd
import smelli
import flavio.plots as fpl # Cheat to get flavio's nice TeX settings
import matplotlib.pyplot as plt

def main(NEW_DELTA_RV=False):
    WC_SCALE = 91.1876
    
    if NEW_DELTA_RV:
        # Update Delta_R^V
        smelli.flavio.default_parameters.set_constraint("DeltaRV", "0.02467(22)") 
    
    neutron_obs = ['R_n', 'D_n', ('lambdaAB_n', 0.581), ('Btilde_n', 0.591), 
                   ('atilde_n', 0.695), 'a_n', ('tau_n', 0.655), ('Atilde_n', 0.559),
                   ('Atilde_n', 0.586)]
    gl = smelli.GlobalLikelihood(include_likelihoods = ("fast_likelihood_quarks.yaml",),
                                 custom_likelihoods={"neutron": neutron_obs})
    if NEW_DELTA_RV:
        print("Re-calculating SM covariance matrix with updated DeltaRV")  
        gl.make_measurement(force=True)
    
    print("Getting all the data for plotting")
    def wc_fct(LH_ud):
        phiq3_11 = LH_ud / (1e3 * 246.2**2)
        return {"phiq3_11": phiq3_11}
    def LL_dict(LH_ud):
        wc_dict = wc_fct(LH_ud)
        pp = gl.parameter_point(wc_dict, scale=WC_SCALE)
        return pp.log_likelihood_dict()
    x_min, x_max = -2, 0.5
    x = np.linspace(x_min, x_max, num=15)
    LL_all = list(map(LL_dict, x))
    # LL_all is a list of dictionaries, giving loglikelihood at each x value
    # Convert to a dictionary of lists, with each key corresponding to a list of
    # chi^2 values for all x values. The factor of -2 converts from loglikelihood
    # to chi^2
    chi2_data = {
        "quarks": [-2*x["fast_likelihood_quarks.yaml"] for x in LL_all],
        "neutron": [-2*x["custom_neutron"] for x in LL_all],
    }

    print("Pull (relative to experiment) of neutron observables at SM, LH_ud = -1, and the difference")
    NP_point = -1
    SM = gl.parameter_point({}, scale=WC_SCALE).obstable()
    bf = gl.parameter_point(wc_fct(NP_point), scale=WC_SCALE).obstable()
    diff = pd.DataFrame({"SM": SM[SM.index.isin(neutron_obs)]["pull exp."],
                         "LH_ud = -1": bf[bf.index.isin(neutron_obs)]["pull exp."]})
    diff["change"] = diff["SM"] - diff["LH_ud = -1"]
    print(diff.sort_values("change"))
    print("Change in chi^2 of the neutron observables at LH_ud = -1 vs SM")
    print(-2*gl.parameter_point(wc_fct(NP_point), scale=WC_SCALE).log_likelihood_dict()["custom_neutron"])

    print("Plotting the delta chi^2 data")
    plt.figure(figsize=(5,5))
    plt.plot(x, chi2_data["quarks"], label=R"quarks")
    plt.plot(x, chi2_data["neutron"], label=R"neutron")
    plt.xlabel(R"$\left[C_{Hq}^{(3)}\right]_{11} (\mu = M_Z) \times v^2 \times 10^3$")
    plt.ylabel(R"$\Delta \chi^2$")
    plt.legend(loc="best")
    plt.ylim(-5, 5)

    basename = "MWE_neutrons"
    if NEW_DELTA_RV:
        basename += "_new_DeltaRV"
    output_filename = basename + ".pdf"
    print(f"Plotting data into {output_filename}")
    plt.savefig(output_filename, bbox_inches="tight")



if __name__ == "__main__":
    print("Result with default config")
    main(NEW_DELTA_RV=False)
    print("Result with new DeltaRV")
    main(NEW_DELTA_RV=True)


```
The different value of `DeltaRV` is what I was using when I found this, but you get a similar result with the current default value as well (just a smaller chi^2 change)

**Comment by peterstangl** [comment]
If I understand it correctly, your problem is that a set of correlated observables yields a Delta chi^2 that is much larger than the Delta chi^2 that you would get if you neglect the correlations. I think it should be not surprising that this can happen. E.g. if you consider just two correlated observables `O1` and `O2` with uncertainties `sigma1` and `sigma2` and correlation `rho` and define:
```
D1 = ( O1(SM)-O1(exp) )/sigma1
D1' = ( O1(NP)-O1(exp) )/sigma1
D2 = ( O2(SM)-O2(exp) )/sigma2
D2' = ( O2(NP)-O2(exp) )/sigma2
```
Then the Delta chi^2 between SM and NP is given by
```
Delta chi^2 = 1/(1-rho^2) ( D1^2 - D1'^2 + D2^2 - D2'^2 - 2 rho (D1 D2 - D1' D2') )
```
If you neglect the correlation, i.e. you just assume rho=0, then you get
```
Delta chi^2 |_(rho=0) =  D1^2 - D1'^2 + D2^2 - D2'^2
```
Now if you have a point where e.g. `D1=D1'` (i.e. `O1` doesn't change between SM and NP point) and `D2=-D2'` (i.e. `O2` deviates from the experimental value by the same amount at the SM and the NP point, but in different directions), then without correlations, you obviously find `Delta chi^2 |_(rho=0) = 0` and the `Delta chi^2` values for both individual observables also vanish.

But if you consider the full correlated `Delta chi^2`, in this example you would get
```
Delta chi^2 = ( - 4 rho D1 D2 )/(1-rho^2)
```
which is only zero if either `rho`, `D1`, or `D2` is zero, but otherwise it can be big.
(Note that even when `D1` and `D2` are rather small, this can be big if `rho` is close to `1`)

**Comment by MJKirk** [comment]
Fair enough, I hadn't written it down to see the 1 / 1-rho^2 enhancement.
In my case it does seem that the correlations are really very close to 1, so the extra correlation term does give a large contribution.
(Aside: as far as I can tell there is no direct way to access the correlations in flavio, you have to get the covariance and uncertainties separately and then do (schematically)
```python
cov = flavio.sm_covariance(obs)
unc = flavio.sm_uncertainties(obs)
corr = cov / np.outer(unc, unc)
```
and then you have the issue that it doesn't quite match up since you have two separate calculations in `sm_covariance` and `sm_uncertainties` - e.g. I get correlations slightly > 1)

**Comment by peterstangl** [comment]
> (Aside: as far as I can tell there is no direct way to access the correlations in flavio, you have to get the covariance and uncertainties separately and then do (schematically)
> 
> ```python
> cov = flavio.sm_covariance(obs)
> unc = flavio.sm_uncertainties(obs)
> corr = cov / np.outer(unc, unc)
> ```
> 
> and then you have the issue that it doesn't quite match up since you have two separate calculations in `sm_covariance` and `sm_uncertainties` - e.g. I get correlations slightly > 1)

For everything to match up, I think it's best to only use the covariance matrix and to not recompute the uncertainties. The diagonal elements of the covariance matrix are the variances, so the correlation matrix can be computed by
```
cov = flavio.sm_covariance(obs)
unc = np.sqrt(np.diag(cov))
corr = cov / np.outer(unc, unc)
```

**Comment by MJKirk** [comment]
Of course :man_facepalming: 
My observables have correlations of 0.998 or more so the enhancement is ~250 or more, and the delta chi^2 makes more sense.
Thanks Peter!
