### ISSUE TITLE
How to get wilson coefficients

### ISSUE THREAD

**Issue by haolinli1991** [smelli/smelli#41]
Hi,

I would like to know if it is possible to obtain the WET Wilson coefficients at a certain scale with SMEFT Wilson coefficients as input? I spot a method "get_wilson" for the class GlobalLikelihood, would you provide an example of the usage of this method?

I am also curious about the determination of the SM parameters in this package compared to the wilson's. Do you implement an iterative determination of the SM parameters here and take into account the extraction of CKM using the 4 low energy observables? I think this is doable since you can obtain the analytical formula for the Low energy observable as functions of SMEFT Wilson coefficients at the EW scale from https://arxiv.org/abs/1812.08163 if only taking into account leading log running effects in WET.
The CKM here I am referring to is the one that related to the product of the rotation matrices that diagonalization left-handed u and d quarks (i.e. that constructed with the **untilted** W parameters in https://arxiv.org/abs/1812.08163). 

If I am wrong about this matching procedure, It would be really appreciated if you could sketch a bit more about the treatment of the CKM and SM Yukawa in this package, or it would also be really very helpful if you could indicate to me the relevant code blocks in the package so that I could read for the full understanding.

Thanks and Best Regards,
Haolin

**Comment by DavidMStraub** [comment]
> I would like to know if it is possible to obtain the WET Wilson coefficients at a certain scale with SMEFT Wilson coefficients as input? I spot a method "get_wilson" for the class GlobalLikelihood, would you provide an example of the usage of this method?

Smelli uses Wilson for Wilson coefficients. The method you mention is extremely trivial:

```python
def get_wilson(self, wc_dict, scale):
    return Wilson(wc_dict, scale=scale, eft=self.eft, basis=self.basis)
```

> I am also curious about the determination of the SM parameters in this package compared to the wilson's. Do you implement an iterative determination of the SM parameters here and take into account the extraction of CKM using the 4 low energy observables? 

Yes. Isn't this exactly what @peterstangl replied in https://github.com/wilson-eft/wilson/issues/83?

**Comment by haolinli1991** [comment]
> > I would like to know if it is possible to obtain the WET Wilson coefficients at a certain scale with SMEFT Wilson coefficients as input? I spot a method "get_wilson" for the class GlobalLikelihood, would you provide an example of the usage of this method?
> 
> Smelli uses Wilson for Wilson coefficients. The method you mention is extremely trivial:
> 
> ```python
> def get_wilson(self, wc_dict, scale):
>     return Wilson(wc_dict, scale=scale, eft=self.eft, basis=self.basis)
> ```
> 
> > I am also curious about the determination of the SM parameters in this package compared to the wilson's. Do you implement an iterative determination of the SM parameters here and take into account the extraction of CKM using the 4 low energy observables?
> 
> Yes. Isn't this exactly what @peterstangl replied in [wilson-eft/wilson#83](https://github.com/wilson-eft/wilson/issues/83)?

Thanks for your reply, I looked through the code, and find the method **w()** in the class **GlobalLikelihoodPoint** is what I am looking for, which gives the calibrated CKM at the input scale. I think I just need to call the match_run() method for this returned Wilson class to get the Wilson coefficient for the WETs at lower scales.
