### ISSUE TITLE
Observable file unused

### ISSUE THREAD

**Issue by MJKirk** [smelli/smelli#48]
The observable list `observables_bclnu_lfu.yaml` isn't actually used anywhere - it was included in David's initial commit for smelli, but already at that point the observables in it were also in `observables_rd.yaml`, `observables_rds.yaml` and `observables_bctaunu_other.yaml` (I guess David changed his mind at the last minute about the organisation), and it is from those files that the observables get included into smelli. 

Anyway, more than once I have got confused about this file and why it doesn't get included anywhere, and if these observables are missing, etc, so I would just remove it (and of course I can make the PR for this myself).

**Comment by DavidMStraub** [comment]
I'm sure there was a brilliant, secret plan behind it. But I forgot what it was.

**Comment by peterstangl** [comment]
Fixed in PR #50.
