### ISSUE TITLE
D meson charged current decays missing

### ISSUE THREAD

**Issue by MJKirk** [smelli/smelli#49]
None of the charged current D meson decays form flavio are included in smelli. I guess they should have been added in v2 when the rest of the charged current decays where added (which was just after the CKM treatment was improved so you could properly deal with them), as that was when the s->u and d->u were included in smelli.

**Comment by MJKirk** [comment]
FYI I now have a branch with the D decays added but it's mixed up with other changes for a project, so I'll clean it up and make a pull request at some point.

**Comment by peterstangl** [comment]
Fixed in PR #52.
